language: node_js
stage: deploy

node_js:
 - '10.16.0'

install:
  - npm install -g firebase-tools

affter_sucess:
  - firebase deploy --token $FIREBASE_TOKEN
  
sudo: true
dist: trusty 

branches:
 only:
 - master

cache:

  directories:
    - node_modules

before_script:
- npm install -g ionic cordova

script:

-  ionic build --prod --base-href='https://antoniotavares20.github.io/Monitora-Admin/'
#- ionic cordova build browser --prod  --release
 # - ng test --watch false -cc
 # - npm run e2e
 # - ng build --base-href 'https://antoniotavares20.github.io/monitora-mobile/'

deploy:
 provider: pages
 skip-cleanup: true
 github-token: $GITHUB_TOKEN
 keep-history: true
 on:
   branch: master
 local_dir: www

 